version: '3.6'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    ports:
      - "8008:8008"
    environment:
      SYNAPSE_SERVER_NAME: synapse.local
      SYNAPSE_REPORT_STATS: "no"
      UID: ${USERID}
      GID: ${GROUPID}
    tmpfs:
      - /tmp
    volumes: 
      - ./components/synapse/homeserver.yaml:/data/homeserver.yaml:ro
      - ./components/synapse/localhost.log.config:/data/localhost.log.config:ro
      - ./components/synapse/localhost.signing.key:/data/localhost.signing.key:ro

  element:
    build: ./components/element
    ports:
      - "8080:8080"
    user: "${USERID}:${GROUPID}"
    volumes:
      - ./src/matrix-js-sdk:/matrix-js-sdk
      - ./src/matrix-react-sdk:/matrix-react-sdk
      - ./src/element-web:/element-web
      - ./components/element/config.json:/element-config.json:ro

  dimension:
    build: ./components/dimension
    depends_on:
      - nginx
    ports:
      - "8082:8082"
    user: "${USERID}:${GROUPID}"
    volumes:
      - ./src/matrix-dimension:/matrix-dimension
      - ./components/dimension/config:/config:ro

  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - synapse
      - element
    volumes:
      - ./components/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"